# Generated by Django 2.0.4 on 2018-04-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
