# Generated by Django 2.0.4 on 2018-04-28 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photo',
            table=None,
        ),
    ]
